# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x93hI8Rf2dLtwiLRn8qhglj0ACldtiDi
"""

import pandas as pd
import numpy as np
import pandas_datareader as web
from datetime import datetime
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

df=web.DataReader('AAPL', data_source='yahoo', start='2006-10-10', end='2011-12-23')

df

plt.figure(figsize=(12.5,4.5))
plt.plot(df['Adj Close'], label='AAPL')
plt.title('Apple Adj. Close Price History')
plt.xlabel('Oct. 02-2006 To Dec. 30-2011')
plt.ylabel('Adj. Close Price USD ($) ')
plt.legend(loc='upper left')
plt.show()

SMA30=pd.DataFrame()
SMA30['Adj Close Price']=df['Adj Close'].rolling(window=30).mean()
SMA30

SMA100=pd.DataFrame()
SMA100['Adj Close Price']=df['Adj Close'].rolling(window=100).mean()
SMA100

plt.figure(figsize=(12.5,4.5))
plt.plot(df['Adj Close'], label='AAPL')
plt.plot(SMA30['Adj Close Price'], label='SMA30')
plt.plot(SMA100['Adj Close Price'], label='SMA100')
plt.title('Apple Adj. Close Price History')
plt.xlabel('Oct. 02-2006 To Dec. 30-2011')
plt.ylabel('Adj. Close Price USD ($) ')
plt.legend(loc='upper left')
plt.show()

data=pd.DataFrame()
data['AAPL']=df['Adj Close']
data['SMA30']=SMA30['Adj Close Price']
data['SMA100']=SMA100['Adj Close Price']
data

def buy_sell(data):
  sigPriceBuy=[]
  sigPriceSell=[]
  flag=-1

  for i in range(len(data)):
    if data['SMA30'][i] > data['SMA100'][i]:
      if flag!=1:
        sigPriceBuy.append(data['AAPL'][i])
        sigPriceSell.append(np.nan)
        flag=1
      else:
        sigPriceBuy.append(np.nan) 
        sigPriceSell.append(np.nan)
    elif data['SMA30'][i]<data['SMA100'][i]:
        if flag!=0:
          sigPriceBuy.append(np.nan)
          sigPriceSell.append(data['AAPL'][i])
          flag=0
        else:
          sigPriceBuy.append(np.nan)
          sigPriceSell.append(np.nan)
    else:   
           sigPriceBuy.append(np.nan) 
           sigPriceSell.append(np.nan)
  return (sigPriceBuy, sigPriceSell)

buy_sell=buy_sell(data)
data['Buy Signal Price']=buy_sell[0]
data['Sell Signal Price']=buy_sell[1]
data

plt.figure(figsize=(12.6,4.6))
 plt.plot(data['AAPL'], label='AAPL', alpha=0.35)
 plt.plot(data['SMA30'], label='SMA30', alpha=0.35)
 plt.plot(data['SMA100'], label='SMA100', alpha=0.35)
 plt.scatter(data.index, data['Buy Signal Price'], label='Buy', marker='^', color='green', s=200)
 plt.scatter(data.index, data['Sell Signal Price'], label='Buy', marker='^', color='red', s=200)
 plt.title('Apple Adj. Close Price History Buy & Sell Signals')
 plt.xlabel('Oct. 02,2016 - Dec. 30,2011')
 plt.ylabel('Adj. Close Price USD ($)')
 plt.legend(loc='upper left')
 plt.show()

